name: Release HKKNX Docker Image

on:
  workflow_dispatch:

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Latest HKKNX Release
        id: release
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: brutella
          repo: hkknx-public
      - name: Check Image    
        id: image
        run: |
          docker manifest inspect ${{ secrets.DOCKERHUB_USERNAME }}/hkknx:${{ steps.release.outputs.latest_tag }} && echo "IMAGE_EXISTS=true" >> $GITHUB_ENV || true
      - name: Build and push
        if: env.IMAGE_EXISTS == null
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:hkknx"
          platforms: linux/amd64,linux/arm
          build-args: |
            HKKNX=${{ steps.release.outputs.latest_tag }}
          push: true
          tags: bugroger/hkknx:latest,bugroger/hkknx:${{ steps.release.outputs.latest_tag }}
