name: HKKNX Docker Image CI

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest HKKNX Release
        id: hkknx-public_releases
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: brutella
          repo: hkknx-public
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          HKKNX: ${{ steps.hkknx-public_releases.outputs.latest_tag }}
        with:
          context: "{{defaultContext}}:hkknx"
          platforms: linux/amd64,linux/arm
          push: true
          tags: bugroger/hkknx:latest,bugroger/hkknx:${{ steps.hkknx-public_releases.outputs.latest_tag }}
